spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ratingMicroservice
      #driver-class-name: mongodb.jdbc.MongoDriver
  
  
  application:
     name: RATING-SERVICE   
     
  config:
    import: optional:configserver:http://localhost:8085      
  
server:
  port: 8083       
  
  
  
  
  
     